language: perl
perl:
  - "5.16"
env:
  global:
  - TIMEOUT=1000

before_install:
- git config --global credential.helper 'cache --timeout 600'
- echo $GOPATH
- echo $GOROOT
install:
- go get ... &
- ls -la
- pwd
- echo $GOPATH
- echo $GOROOT


before_script:
- go get ... &
- echo $GOPATH
- echo $GOROOT


script:
- pwd
- ls -la
- echo "script run"
- echo $GOPATH
- ls -la $GOPATH
- echo $GOROOT

after_success:
- echo $GOPATH
- ls -la $GOPATH
- echo $GOROOT

- echo "PR $TRAVIS_PULL_REQUEST"
- if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
- echo $GOPATH
- ls -la $GOPATH